version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
      - "traefik.tcp.routers.mysql.service=mysql"
      # - "traefik.tcp.routers.mysql.tls=true"
      - "traefik.tcp.services.mysql.loadbalancer.server.port=3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-testdb}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_USER:-dbpassword}
    # ports:
    #   - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web

volumes:
  mysql_data:
  

networks:
  web:
    external: true
  